version: '3.8'

services:
  auth-service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - API_KEY_SECRET=${API_KEY_SECRET}
      - JWT_SECRET=${JWT_SECRET}
      - DB_URL=jdbc:oracle:thin:@oracle-db:1521/XEPDB1
      - DB_USERNAME=admin
      - DB_PASSWORD=secureDbPass
    depends_on:
      oracle-db:
        condition: service_healthy
    networks:
      - auth-network
    restart: unless-stopped

  oracle-db:
    image: gvenzl/oracle-xe:21-slim
    environment:
      - ORACLE_PASSWORD=secureDbPass
      - APP_USER=admin
      - APP_USER_PASSWORD=secureDbPass
    volumes:
      - oracle-data:/opt/oracle/oradata
    ports:
      - "1521:1521"
    networks:
      - auth-network
    healthcheck:
      test: ["CMD-SHELL", "echo 'SELECT 1 FROM DUAL;' | sqlplus -s admin/secureDbPass@localhost:1521/XEPDB1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s
    restart: unless-stopped

volumes:
  oracle-data:

networks:
  auth-network:
    driver: bridge
